language: dart
dart:
  - dev

branches:
  only: 
    - master
    - release

jobs:
  include:
    - stage: build
      script: bash ./tool/build.sh
    - stage: deploy
      script: bash ./tool/publish.sh

stages:
  - build
  - name: deploy
    if: branch = release

cache:
  directories:
    - $HOME/.pub-cache