language: dart
dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings .
  - dartfmt:

before_script:
  - pub run build_runner build --delete-conflicting-outputs

after_success:
  - ./tool/publish.sh