# Created with package:mono_repo v1.2.1
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master
    - v1_x

jobs:
  include:
    - stage: analyze
      name: "SDK: dev - DIR: reflutter - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="reflutter"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: reflutter - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="reflutter"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: reflutter_generator - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="reflutter_generator"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: reflutter_generator - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="reflutter_generator"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: reflutter_test - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="reflutter_test"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: reflutter_test - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="reflutter_test"
      dart: dev

stages:
  - analyze

cache:
  directories:
    - "$HOME/.pub-cache"
    - reflutter_generator/.dart_tool/build
    - reflutter_test/.dart_tool/build
