language: dart
dart:
  - dev

dart_task:
  - pub: run build_runner build --delete-conflicting-outputs
  - dartanalyzer: --fatal-warnings .
  - dartfmt:

deploy:
  provider: script
  script: ./tool/publish.sh
  on:
    branch: release