language: dart
dart:
  - dev

branches:
  only: 
    - master
    - release

jobs:
  include:
    - stage: prepublish
      script: ./tool/prepublish
    - stage: publish
      script: bash ./tool/publish.sh

stages:
  - prepublish
  - publish

cache:
  directories:
    - $HOME/.pub-cache