language: dart
dart:
  - dev

dart_task:
  - pub: get
  - pub: run build_runner build --delete-conflicting-outputs
  - dartanalyzer: --fatal-warnings
  - dartfmt:

deploy:
  provider: script
  script: pub publish
  on:
    branch: release