# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: analyze_and_format
      script: ./tool/travis.sh command_0
      env: PKG="reflutter"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="reflutter"
      dart: dev
    - stage: publish
      script: ./tool/travis.sh command_1
      env: PKG="reflutter"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh command_0
      env: PKG="reflutter_generator"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="reflutter_generator"
      dart: dev
    - stage: publish
      script: ./tool/travis.sh command_1
      env: PKG="reflutter_generator"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh command_0
      env: PKG="reflutter_test"
      dart: dev
    - stage: analyze_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="reflutter_test"
      dart: dev

stages:
  - analyze_and_format
  - publish

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
