# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      reflutter:
        generate_for: ["example/example.dart", "test/test_api.dart"]

builders:
  reflutter:
    target: ":reflutter"
    import: "package:reflutter/reflutter.dart"
    builder_factories: ["reflutterBuilder"]
    build_extensions: {".dart": [".api.dart"]}
    auto_apply: root_package
    build_to: source