name: flutter_refit
description: A library to generate HTTP API clients.
version: 0.1.0
homepage: https://www.github.com/ctartamella/flutter_refit
author: Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies: 
  http: ^0.11.3
  meta: ^1.1.5
  analyzer: ^0.31.1
  build: ^0.12.6
  code_builder: '>2.3.0 <4.0.0'
  dart_style: ^1.0.14
  logging: ^0.11.3
  source_gen: ^0.8.1
  jaguar_serializer: ^1.0.0-dev7
  jaguar_generator_config: ^0.0.1
  
dev_dependencies:
  build_runner: 0.8.8
  build_config: ^0.2.6
  jaguar_serializer_cli: ^1.0.0-dev8
  test: ^0.12.38

refit_http:
  - example/example.dart
