name: reflutter
description: >
  A library to generate HTTP clients from metadata specified by users.
  The thought is that this can be used by Flutter based mobile apps to
  connect to their backend resources.
homepage: https://www.github.com/ctartamella/reflutter
version: 0.2.2
author: Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies: 
  http: ^0.11.3
  meta: ^1.1.5
  analyzer: ^0.31.1
  build: ^0.12.4
  code_builder: '>2.3.0 <4.0.0'
  dart_style: ^1.0.14
  logging: ^0.11.3
  source_gen: ^0.8.1
  jaguar_serializer: ^1.0.0-dev7
  jaguar_generator_config: ^0.0.1
  
dev_dependencies:
  build_runner: 0.8.8
  build_config: ^0.2.6
  jaguar_serializer_cli: ^1.0.0-dev8
  test: ^0.12.38