name: flutter_refit
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.example.com
author: Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.48.0'

executables:
  refit_http:

dependencies: 
  code_builder: ^1.0.4
  source_gen:
  analyzer:
  
dev_dependencies:
  build_runner:
  build_config:  
  test:

refit_http:
  - example/example.dart
