# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  flutter_refit_cli:
    target: ":flutter_refit_cli"
    import: "package:flutter_refit_cli/flutter_refit_cli.dart"
    builder_factories: ["refitHttpPartBuilder"]
    build_extensions: {".dart": [".jser.dart"]}
    auto_apply: root_package
    build_to: source