name: flutter_refit_cli
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.example.com
author: Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

executables:
  refit_http:

dependencies: 
  jaguar_serializer: ^1.0.0-dev7
  jaguar_generator_config:

dev_dependencies:
  code_builder: '>2.3.0 <4.0.0'
  source_gen: ^0.8.1
  analyzer: ^0.31.1
  build_runner: 0.8.8
  build_config: ^0.2.6
  flutter_refit: ^0.0.1
  jaguar_serializer_cli: ^1.0.0-dev8
  test: ^0.12.38

dependency_overrides:
  flutter_refit:
    path: ../flutter_refit

refit_http:
  - example/example.dart
